---
title: "Module 2-1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction to the problem  
Overall, the issue here is that we have a wave of people getting sick across 
the team. People are coming in complaining of stomach sickness - doctors have 
ruled out a communicable viral infection like norovirus, and it seems to be a 
food contamination issue.  

The two main sources of food that are grown on site and distributed to team 
members are [plants grown in hydroponic greenhouses](https://thespoon.tech/scientists-in-antarctica-grow-food-without-soil-or-sunlight-get-ready-mars/). 
(mostly swiss chard, cucumbers and radishes) and fish (tilapia, a tolerant warm
-water species).  

We have a good set of data on team members that are sick, and how much fish or 
plant material they incorporate into their diets (team members vary in the 
composition of their diet - people are allowed to choose how much of different 
food sources they use).  

## Discussion - how might we figure this out?  
Spend 5 minutes brainstorming in your groups how you might figure out whether 
plants or fish are the culprits? Be ready to report out.  

## Introduction to the dataset and visualization in R  

First we're going to pull in the data and 


